USE [master]
GO

/****** Object:  Database [LIMEBASE]    Script Date: 24.06.2013 18:03:27 ******/
CREATE DATABASE [LIMEBASE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LIMEBASE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MAINPCSQL\MSSQL\DATA\LIMEBASE.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LIMEBASE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MAINPCSQL\MSSQL\DATA\LIMEBASE_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LIMEBASE] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LIMEBASE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LIMEBASE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LIMEBASE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LIMEBASE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LIMEBASE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LIMEBASE] SET ARITHABORT OFF 
GO

ALTER DATABASE [LIMEBASE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LIMEBASE] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LIMEBASE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LIMEBASE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LIMEBASE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LIMEBASE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LIMEBASE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LIMEBASE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LIMEBASE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LIMEBASE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LIMEBASE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LIMEBASE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LIMEBASE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LIMEBASE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LIMEBASE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LIMEBASE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LIMEBASE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LIMEBASE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LIMEBASE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LIMEBASE] SET  MULTI_USER 
GO

ALTER DATABASE [LIMEBASE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LIMEBASE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LIMEBASE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LIMEBASE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LIMEBASE] SET  READ_WRITE 
GO


